version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: translator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/translator
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 111
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["java", "-jar", "/app/translator.jar"]

  flyway:
    image: flyway/flyway:latest
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres/translator
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: 111
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
    entrypoint: ["flyway", "migrate"]

volumes:
  postgres_data:
