spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/translator
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://postgres:5432/translator
    user: postgres
    password: 111
  translator:
    google:
      url: "https://translate.googleapis.com/translate_a/single?client=gtx&sl={sourceLanguage}&tl={targetLanguage}&dt=t&q={word}"